name: "CD - Production Deployment"

concurrency: 1

on:
  push:
    branches: [main]

jobs:
  deploy-prod:
    name: "Deploy to production"
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4

      - uses: databricks/setup-cli@main

      - name: Validate bundle
        run: databricks bundle validate -t prod
        env:
          DATABRICKS_TOKEN: ${{ secrets.PROD_DATABRICKS_TOKEN }}
          DATABRICKS_HOST: ${{ secrets.PROD_DATABRICKS_HOST }}

      - name: Deploy bundle to production
        run: databricks bundle deploy -t prod --auto-approve
        env:
          DATABRICKS_TOKEN: ${{ secrets.PROD_DATABRICKS_TOKEN }}
          DATABRICKS_HOST: ${{ secrets.PROD_DATABRICKS_HOST }}
