name: "CI - Validate & Test"

concurrency: 1

on:
  pull_request:
    types: [opened, synchronize]
    branches: [main]

jobs:
  validate:
    name: "Validate bundle"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: databricks/setup-cli@main

      - name: Validate bundle (dev)
        run: databricks bundle validate
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}

      - name: Validate bundle (prod)
        run: databricks bundle validate -t prod
        env:
          DATABRICKS_TOKEN: ${{ secrets.PROD_DATABRICKS_TOKEN }}
          DATABRICKS_HOST: ${{ secrets.PROD_DATABRICKS_HOST }}

  deploy-dev:
    name: "Deploy to dev"
    runs-on: ubuntu-latest
    needs: [validate]
    steps:
      - uses: actions/checkout@v4

      - uses: databricks/setup-cli@main

      - name: Deploy bundle to dev
        run: databricks bundle deploy
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
